# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run an ML Pipeline

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest

    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      env:
        repo_token: ${{secrets.GITHUB_TOKEN}}
      run: |
        sudo bash ./script.sh
        chmod +rx script.sh
        var_c=$(./script.sh)
        echo $var_c
        pip install -r requirements.txt
        dvc repro
        git fetch --prune
        dvc metrics diff --show-md master script > report.md
        # Add figure to the report
        echo "## Validating results by region" >> report.md
        cml-publish by_region.png --md >> report.md
        cml-send-comment report.md
