# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Riun an ML Pipeline

on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest

    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      run: |
        pip install -r requirements.txt
        dvc repro

        git fetch --prune
        dvc metrics diff --show-md master > report.md

        cml-publish by_region.png --md >report.md
        cml-send-comment report.md