# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run an ML Pipeline

on: [push]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name: repo_branch
        env:
          repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          sudo bash ./script.sh
        id: repo_branch_id

      - name: cml_run
        env:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          BRANCH: ${{steps.repo_branch_id.outputs.*}}
        run: |
          echo $BRANCH
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md master > report.md

          cml-publish by_region.png --md >report.md
          cml-send-comment report.md
